"""
MARLIN-Twin: Maritime Adaptive Resilience Learning with Integrated Networked Twins
"""

__version__ = "0.1.0"

from marlin_twin.data_classes import (
    VesselType,
    COLREGsRule,
    EncounterType,
    MessagePriority,
    CommunicationStatus,
    NavigationMode,
    EnvironmentCondition,
    VesselState,
    VesselDynamics,
    VesselSpecification,
    Waypoint,
    Route,
    Encounter,
    VesselObservation,
    VesselAction,
    MaritimeMessage,
    MaritimeCommunicationChannel,
    VesselAgent,
    AISReading,
    RadarTrack,
    VesselStateEstimate,
    MaritimeDigitalTwin,
    DigitalTwinConfig,
    EncounterGraph,
    MaritimeScene,
    SceneTransition,
    VoyageEpisode,
    CoordinationResilienceMetrics,
    GracefulDegradationReport,
    MaritimeExperimentConfig,
    MaritimeExperimentResult,
)

from marlin_twin.api import (
    MarlinTwinAPI,
    create_default_api,
    create_minimal_api,
)

__all__ = [
    "MarlinTwinAPI",
    "create_default_api",
    "create_minimal_api",
    "VesselType",
    "COLREGsRule",
    "EncounterType",
    "MessagePriority",
    "CommunicationStatus",
    "NavigationMode",
    "EnvironmentCondition",
    "VesselState",
    "VesselDynamics",
    "VesselSpecification",
    "Waypoint",
    "Route",
    "Encounter",
    "VesselObservation",
    "VesselAction",
    "MaritimeMessage",
    "MaritimeCommunicationChannel",
    "VesselAgent",
    "AISReading",
    "RadarTrack",
    "VesselStateEstimate",
    "MaritimeDigitalTwin",
    "DigitalTwinConfig",
    "EncounterGraph",
    "MaritimeScene",
    "SceneTransition",
    "VoyageEpisode",
    "CoordinationResilienceMetrics",
    "GracefulDegradationReport",
    "MaritimeExperimentConfig",
    "MaritimeExperimentResult",
]
